/**
 * Generates the `harness-workspace.yml` content for a freshly procured
 * project.
 *
 * The minimal generator below produces a YAML config that is *just enough*
 * to spawn a job — workspace.id, one product with the user's repos, and
 * the standard worker/worktree defaults. It does NOT mirror every section
 * of `workspace-template/harness-workspace.yml.example` because most of
 * those sections (servers config, worker resources, worktree pruneAfter,
 * etc.) have sensible defaults baked into the harness-server / spawn-worker
 * code paths and don't need to be templated unless you want to override.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * TODO(you): extend this generator to template the additional fields YOUR
 * future projects will want to customize at procure time. Candidates:
 *
 *   1. workspace.worker.defaultResources    — bump memory/cpu for big repos?
 *   2. workspace.worktree.pruneAfter        — shorter for low-disk machines?
 *   3. per-product pipeline overrides       — register a pipeline catalog?
 *   4. workspace.servers.{harness,memory,context}.port   — non-default ports?
 *
 * Concrete extension points marked below with "// EXTEND:" comments. Each is
 * a 1–3 line addition. Keep the function pure — it takes a ProcureSpec, returns
 * a string. No I/O, no env reads, no CLI flag mutation here.
 * ─────────────────────────────────────────────────────────────────────────
 */

import YAML from 'yaml';
import type { ProcureSpec } from './types.ts';

export function generateWorkspaceYml(spec: ProcureSpec): string {
  const config = {
    workspace: {
      id: spec.name,

      // Servers section — uses defaults from workspace-template's
      // harness-workspace.yml.example. Most projects don't customize these.
      servers: {
        harness: {
          image: 'agentx/harness-server:0.0.0',
          port: 7700,
          unixSocket: '.harness/run/harness.sock',
        },
        memory: {
          image: 'agentx/edge-memory-server:0.0.0',
          port: 7710,
          unixSocket: '.harness/run/memory.sock',
          backend: 'echo',
        },
        context: {
          image: 'agentx/edge-context-server:0.0.0',
          port: 7720,
          unixSocket: '.harness/run/context.sock',
          backend: 'echo',
        },
      },

      worker: {
        image: 'agentx/worker:0.0.0',
        devcontainerPath: '.devcontainer/worker',
        namingPattern: 'agentx-job-${jobId}',
        defaultResources: {
          memory: '4Gi',
          cpu: 2,
        },
        // EXTEND: bump defaultResources here if your repo needs more headroom
      },

      worktree: {
        rootDir: '.harness/wt',
        pathSchema: '${jobId}/${subagentId}/${repoName}',
        keepOnSuccess: true,
        keepOnFailure: false,
        pruneAfter: '7d',
        branchTemplate: 'agent/${jobId}',
        // EXTEND: shorter pruneAfter for low-disk machines
      },

      products: [
        {
          id: spec.name,
          description: `${spec.name} — generated by agentx-workspace on ${new Date().toISOString().slice(0, 10)}`,
          repos: spec.repos.map((r) => ({
            name: r.name,
            cloneUrl: r.cloneUrl,
            baseRef: r.baseRef ?? 'main',
            path: `/workspace/${r.name}`,
          })),
          // EXTEND: per-product pipeline registration could land here
        },
      ],
    },
  };

  return YAML.stringify(config, { indent: 2, lineWidth: 100 });
}
