package com.jefelabs.agentx.controlplane.proposals.domain;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * A proposed skill — typically generated by an agent's post-job
 * reflection ("I needed a tool for X but didn't have one"). Reviewed
 * by an admin, then either approved (creates a draft entry in
 * {@code catalog_items}) or rejected.
 */
public record SkillProposal(
    UUID id,
    String orgId,
    /** Job whose reflection produced this proposal; null if admin-authored. */
    String sourceJobId,
    String name,
    String description,
    String rationale,
    /** e.g., 'tool', 'integration', 'task', 'workflow'. */
    String category,
    List<String> tags,
    ProposalStatus status,
    String reviewer,
    Instant reviewedAt,
    String rejectionReason,
    /** Set when status=approved and a draft was seeded into catalog_items. */
    String catalogItemId,
    Instant createdAt
) {
}
