package com.jefelabs.agentx.controlplane.catalog.integration;

import com.jefelabs.agentx.controlplane.catalog.domain.CatalogItem;
import com.jefelabs.agentx.controlplane.catalog.domain.CatalogItemType;
import com.jefelabs.agentx.controlplane.catalog.service.CatalogItemService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;
import org.springframework.stereotype.Component;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

/**
 * Bootstrap loader for the unified catalog. On
 * {@link ApplicationReadyEvent}, if the catalog is empty for the
 * configured bootstrap org, reads
 * {@code seed-catalog-items.json} from the classpath and upserts
 * every entry. The seed file is regenerated by
 * {@code controlplane/scripts/regen-catalog-seed.sh} from the
 * agentx-skillz repo's catalog/ tree.
 *
 * <p>Subsequent restarts no-op (catalog non-empty). To re-seed:
 * truncate the catalog_items table or set
 * {@code agentx.catalog.bootstrap.force=true} for one boot.
 */
@Component
public class CatalogBootstrap {

    private static final Logger log = LoggerFactory.getLogger(CatalogBootstrap.class);
    private static final String SEED_RESOURCE = "classpath:seed-catalog-items.json";

    private final CatalogItemService service;
    private final ObjectMapper objectMapper;
    private final String bootstrapOrgId;
    private final boolean force;

    public CatalogBootstrap(
        CatalogItemService service,
        ObjectMapper objectMapper,
        @Value("${agentx.catalog.bootstrap.org-id:dev-org}") String bootstrapOrgId,
        @Value("${agentx.catalog.bootstrap.force:false}") boolean force
    ) {
        this.service = service;
        this.objectMapper = objectMapper;
        this.bootstrapOrgId = bootstrapOrgId;
        this.force = force;
    }

    @EventListener(ApplicationReadyEvent.class)
    public void seedFromClasspath() {
        long existing = service.countByOrg(bootstrapOrgId);
        if (existing > 0 && !force) {
            log.info("Catalog bootstrap skipped: org={} already has {} item(s); set agentx.catalog.bootstrap.force=true to re-seed",
                bootstrapOrgId, existing);
            return;
        }

        List<SeedEntry> seed = loadSeed();
        if (seed.isEmpty()) {
            log.warn("Catalog bootstrap skipped: seed file empty or missing");
            return;
        }

        int inserted = 0;
        for (SeedEntry e : seed) {
            try {
                service.upsert(new CatalogItem(
                    bootstrapOrgId,
                    CatalogItemType.fromDbValue(e.type()),
                    e.id(), e.name(), e.version(), e.description(),
                    e.topic(), e.tags(), e.runtime(),
                    e.manifest(), "skillzkit",
                    null, null
                ));
                inserted++;
            } catch (RuntimeException err) {
                log.warn("Catalog bootstrap: skipped {}/{} ({})", e.type(), e.id(), err.getMessage());
            }
        }
        log.info("Catalog bootstrap: seeded {} of {} item(s) into org={}",
            inserted, seed.size(), bootstrapOrgId);
    }

    private List<SeedEntry> loadSeed() {
        try {
            Resource[] resources = new PathMatchingResourcePatternResolver()
                .getResources(SEED_RESOURCE);
            if (resources.length == 0 || !resources[0].exists()) {
                return List.of();
            }
            try (InputStream in = resources[0].getInputStream()) {
                JsonNode arr = objectMapper.readTree(in);
                if (!arr.isArray()) return List.of();
                List<SeedEntry> out = new ArrayList<>();
                for (JsonNode entry : arr) {
                    out.add(new SeedEntry(
                        entry.path("type").asText(),
                        entry.path("id").asText(),
                        entry.path("name").asText(),
                        entry.path("version").asText(null),
                        entry.path("description").asText(null),
                        entry.path("topic").asText(null),
                        toStringList(entry.path("tags")),
                        entry.path("runtime").asText(null),
                        entry.get("manifest")
                    ));
                }
                return out;
            }
        } catch (IOException ex) {
            log.warn("Catalog bootstrap: failed to read seed-catalog-items.json: {}", ex.getMessage());
            return List.of();
        }
    }

    private static List<String> toStringList(JsonNode node) {
        if (node == null || !node.isArray()) return List.of();
        List<String> out = new ArrayList<>(node.size());
        for (JsonNode el : node) {
            if (el.isTextual()) out.add(el.asText());
        }
        return out;
    }

    private record SeedEntry(
        String type,
        String id,
        String name,
        String version,
        String description,
        String topic,
        List<String> tags,
        String runtime,
        JsonNode manifest
    ) {}
}
