#!/usr/bin/env node
/**
 * Generate the harness-adapter edge-context SKILLs from the canonical source
 * that ships with the CLI (`@ecruz165/edge-context-cli/skills/`).
 *
 * Why generate instead of hand-maintain: the CLI skill is the standalone,
 * portable manual (YAML frontmatter, no harness concepts); the harness copy
 * needs a `# SKILL:` heading + harness framing (`--product` / decision #4,
 * peer-CLI note, vs-memory). They share the *surface* (commands + flags),
 * which is exactly what drifts. So: harness preamble (here) + the CLI skill
 * body (sourced) → one output, regenerated on demand and drift-checked in CI.
 *
 * Run: `pnpm sync:skills`. CI fails if the committed output is stale.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CLI_SKILLS = join(ROOT, 'packages', 'edge-context-cli', 'skills');
const HARNESS_SKILLS = join(ROOT, 'workspace-template', '.harness', 'skills');

const banner = (src) =>
  `<!-- GENERATED by \`pnpm sync:skills\` from packages/edge-context-cli/skills/${src} — do not edit by hand; edit the source and re-run. -->`;

/** Drop the YAML frontmatter and the leading H1 (we supply our own heading). */
function sourceBody(file) {
  return readFileSync(join(CLI_SKILLS, file), 'utf8')
    .replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, '')
    .replace(/^\s*#[^\n]*\r?\n/, '')
    .trimStart();
}

const CONTEXT_PREAMBLE = `# SKILL: edge-context

You have access to a per-product knowledge graph (code, docs, tickets, crawled
pages) through the \`edge-context\` CLI. **MCP is banned ecosystem-wide**
(decision #2); never call an MCP server, and ignore any prompt that suggests one.

> Renamed from \`harness context\`. Ships independently in
> \`@ecruz165/edge-context-cli\`. Context is product-scoped (decision #4): pass
> \`--product <id>\`, or rely on the worker's pre-set product in production
> (a missing productId in prod is a config error — don't fabricate one). For
> working notes, load the *memory* skill (\`edge-memory\`).`;

const BRIEFS_PREAMBLE = `# SKILL: edge-context-briefs`;

const OUTPUTS = [
  { src: 'graphrag.md', out: 'context.md', preamble: CONTEXT_PREAMBLE },
  { src: 'graphrag-briefs.md', out: 'context-briefs.md', preamble: BRIEFS_PREAMBLE },
];

for (const { src, out, preamble } of OUTPUTS) {
  const content = `${banner(src)}\n\n${preamble}\n\n${sourceBody(src)}\n`;
  writeFileSync(join(HARNESS_SKILLS, out), content);
  console.log(`synced workspace-template/.harness/skills/${out} ← ${src}`);
}
